# no version needed since 2020

services:
  # flask:
  #   image: python
  #   command: bash -c "pip install -r requirements.txt && FLASK_APP=app.py FLASK_DEBUG=1 flask run --host 0.0.0.0"
  #   working_dir: /site
  #   volumes:
  #     - .:/site
  #   ports:
  #     - '5000:5000'

  flask:
    build:
      dockerfile: Dockerfile
    ports:
      - '80:80'